import { parseNoun } from './noun';

test('noun singular', () => {
    const actual = parseNoun(
        {
            word: 'belfry',
            alternativeForms: [],
            derivedTerms: [],
            relatedTerms: [],
            pronunciations: [{ tags: [], ipa: '/ˈbɛlfɹi/' }],
            rhymes: [],
            anagrams: [],
            etymology:
                "From {{inh|en|enm|belfrey}}, {{m|enm|bellfray}}, {{m|enm|belfray}}, from {{der|en|fro|belfroi}}, {{m|fro|berfroi}}, {{m|fro|berfrey}} (changed to have an l by association with [[bell]]), from {{der|en|gmh|-}} {{m|gmh|bërcvrit||'mountain peace', a defensive tower}} / {{m|gmh|bërvrit}},<ref>[http://www.etymonline.com/index.php?search=belfry&searchmode=none belfry] in [[:w:Online Etymology dictionary|Online Etymology dictionary]]</ref><ref>{{R:Webster 1913|belfry}}</ref><ref>[http://germazope.uni-trier.de/Projects/WBB/woerterbuecher/bmz/wbgui?lemmode=lemmasearch&mode=linking&textsize=600&onlist=&word=bercfrit&lemid=BB00462&query_start=1&totalhits=0&textword=&locpattern=&textpattern=&lemmapattern=&verspattern= Alternative spelling] and languages with loanwords from the Middle High German word, in [[:w:de:Georg Friedrich Benecke|Benecke]]'s ''Mittelhochdeutsches Wörterbuch''</ref> possibly via {{der|en|LL.|berefredus}}, from {{der|en|gem-pro|*bergafriþuz}}, from {{der|en|ine-pro|*bʰerĝʰ}}, {{m|ine-pro|*bʰr̥ĝʰ}} + {{m|ine-pro|*prāy-}}, {{m|ine-pro|*prēy-||to like, love}}.",
        },
        {
            _content: [
                '{{en-noun|belfries}}',
                '',
                '# {{lb|en|obsolete}} A movable [[tower]] used in [[sieges]].',
                '# {{lb|en|dialectal}} A [[shed]].',
                '# {{lb|en|obsolete}} An alarm-tower; a [[watchtower]] containing an alarm-bell.',
                '# {{lb|en|architecture}} A tower or steeple specifically for containing bells, especially as part of a church.',
                '# {{lb|en|architecture}} A part of a large tower or steeple, specifically for containing bells.',
                "#* {{RQ:Joyce Ulysses}} Episode 12, ''The Cyclops''",
                "#*: From the '''belfries''' far and near the funereal deathbell tolled unceasingly while all around the gloomy precincts rolled the ominous warning of a hundred muffled drums punctuated by the hollow booming of pieces of ordnance.",
                '',
            ],
            Derived_terms: {
                _content: [
                    "* {{l|en|have bats in one's belfry}}, {{l|en|have bats in the belfry}}",
                    '',
                ],
                _objects: [
                    ['l', 'en', "have bats in one's belfry"],
                    ['l', 'en', 'have bats in the belfry'],
                ],
            },
            Translations: {
                _content: [
                    '{{trans-top|moveable tower used in sieges}}',
                    '* Bulgarian: {{t|bg|обсадна кула}}',
                    '* Finnish: {{t|fi|piiritystorni}}',
                    '{{trans-mid}}',
                    '* French: {{t+|fr|beffroi|m}}',
                    '{{trans-bottom}}',
                    '',
                    '{{trans-top|watchtower containing an alarm-bell}}',
                    '* Bulgarian: {{t|bg|наблюдателна кула}}',
                    '* Dutch: {{t+|nl|belfort|n}}',
                    '{{trans-mid}}',
                    '* Finnish: {{t+|fi|kellotorni}}',
                    '* French: {{t+|fr|beffroi|m}}',
                    '* Interlingue: {{t|ie|cloch-turre}}, {{t|ie|clochiere}}',
                    '{{trans-bottom}}',
                    '',
                    '{{trans-top|tower or steeple specifically for containing bells, especially as part of a church}}',
                    '* Bulgarian: {{t|bg|камбанария}}',
                    '* Dutch: {{t+|nl|klokkentoren|m}}',
                    '* Finnish: {{t+|fi|kellotorni}}',
                    '* French: {{t+|fr|beffroi|m}}',
                    '* Friulian: {{t|fur|cjampanîli}}, {{t|fur|cjampanili}}, {{t|fur|cjampanîl}}, {{t|fur|cjampanil}}',
                    '* Greek: {{t+|el|καμπαναριό|n}}, {{t+|el|κωδωνοστάσιο|n}}',
                    '* Hungarian: {{t+|hu|harangtorony}}',
                    '* Irish: {{t|ga|clogás|m}}',
                    '* Istriot: {{t|ist|canpaneîl}}, {{t|ist|canpanèil}}',
                    '* Italian: {{t+|it|campanile|m}}',
                    '* Japanese: {{t+|ja|鐘楼|tr=しょうろう, shōrō}}',
                    '{{trans-mid}}',
                    '* Manx: {{t|gv|claggys|m}}, {{t|gv|thie cluig|m}}, {{t|gv|shamyr chluig|f}}',
                    '* Maori: {{t|mi|pourewa pere}}',
                    '* Polish: {{t+|pl|dzwonnica|f}}',
                    '* Portuguese: {{t+|pt|campanário|m}}, {{t|pt|torre sineira|f}}',
                    '* Romansch: {{t|rm|clutger|m}} {{qualifier|Rumantsch Grischun, Sursilvan, Sutsilvan, Surmiran}}, {{t|rm|clucher|m}} {{qualifier|Puter, Vallader}}',
                    '* Russian: {{t+|ru|колоко́льня|f}}',
                    '* Spanish: {{t|es|campanil}}, {{t+|es|campanario}}',
                    '* Swedish: {{t+|sv|klocktorn}}',
                    '* Tagalog: {{t|tl|batingawan}}',
                    '* Ukrainian: {{t+|uk|дзвіни́ця|f}}',
                    '* Venetian: {{t|vec|canpanil}}, {{t|vec|canpanile}}, {{t|vec|canpanièl}}, {{t|vec|canpaniłe}}',
                    '{{trans-bottom}}',
                    '',
                    '{{trans-top|part of a large tower or steeple, specifically for containing bells}}',
                    '* Bulgarian: {{t|bg|камбанария}}',
                    '* Finnish: {{t+|fi|kellotorni}}',
                    '* German: {{t+|de|Glockenstube|f}}',
                    '* Greek: {{t+|el|κωδωνοστάσιο|n}}',
                    '* Irish: {{t|ga|clogás|m}}',
                    '* Japanese: {{t+|ja|鐘楼|tr=しょうろう, shōrō}}',
                    '* Maori: {{t|mi|pourewa pere}}',
                    '{{trans-mid}}',
                    '* Norwegian:',
                    '*: Bokmål: {{t|nb|klokkerom|n}}',
                    '*: Nynorsk: {{t|nn|klokkerom|n}}',
                    '* Portuguese: {{t+|pt|campanário|m}}',
                    '* Romansch: {{t|rm|clutger|m}} {{qualifier|Rumantsch Grischun, Sursilvan, Sutsilvan, Surmiran}}, {{t|rm|clucher|m}} {{qualifier|Puter, Vallader}}',
                    '* Spanish: {{t+|es|campanario|m}}',
                    '* Tagalog: {{t|tl|batingawan}}',
                    '{{trans-bottom}}',
                    '',
                ],
                _objects: [
                    ['trans-top', 'moveable tower used in sieges'],
                    ['t', 'bg', 'обсадна кула'],
                    ['t', 'fi', 'piiritystorni'],
                    ['trans-mid'],
                    ['t+', 'fr', 'beffroi', 'm'],
                    ['trans-bottom'],
                    ['trans-top', 'watchtower containing an alarm-bell'],
                    ['t', 'bg', 'наблюдателна кула'],
                    ['t+', 'nl', 'belfort', 'n'],
                    ['trans-mid'],
                    ['t+', 'fi', 'kellotorni'],
                    ['t+', 'fr', 'beffroi', 'm'],
                    ['t', 'ie', 'cloch-turre'],
                    ['t', 'ie', 'clochiere'],
                    ['trans-bottom'],
                    [
                        'trans-top',
                        'tower or steeple specifically for containing bells, especially as part of a church',
                    ],
                    ['t', 'bg', 'камбанария'],
                    ['t+', 'nl', 'klokkentoren', 'm'],
                    ['t+', 'fi', 'kellotorni'],
                    ['t+', 'fr', 'beffroi', 'm'],
                    ['t', 'fur', 'cjampanîli'],
                    ['t', 'fur', 'cjampanili'],
                    ['t', 'fur', 'cjampanîl'],
                    ['t', 'fur', 'cjampanil'],
                    ['t+', 'el', 'καμπαναριό', 'n'],
                    ['t+', 'el', 'κωδωνοστάσιο', 'n'],
                    ['t+', 'hu', 'harangtorony'],
                    ['t', 'ga', 'clogás', 'm'],
                    ['t', 'ist', 'canpaneîl'],
                    ['t', 'ist', 'canpanèil'],
                    ['t+', 'it', 'campanile', 'm'],
                    ['t+', 'ja', '鐘楼', 'tr=しょうろう, shōrō'],
                    ['trans-mid'],
                    ['t', 'gv', 'claggys', 'm'],
                    ['t', 'gv', 'thie cluig', 'm'],
                    ['t', 'gv', 'shamyr chluig', 'f'],
                    ['t', 'mi', 'pourewa pere'],
                    ['t+', 'pl', 'dzwonnica', 'f'],
                    ['t+', 'pt', 'campanário', 'm'],
                    ['t', 'pt', 'torre sineira', 'f'],
                    ['t', 'rm', 'clutger', 'm'],
                    [
                        'qualifier',
                        'Rumantsch Grischun, Sursilvan, Sutsilvan, Surmiran',
                    ],
                    ['t', 'rm', 'clucher', 'm'],
                    ['qualifier', 'Puter, Vallader'],
                    ['t+', 'ru', 'колоко́льня', 'f'],
                    ['t', 'es', 'campanil'],
                    ['t+', 'es', 'campanario'],
                    ['t+', 'sv', 'klocktorn'],
                    ['t', 'tl', 'batingawan'],
                    ['t+', 'uk', 'дзвіни́ця', 'f'],
                    ['t', 'vec', 'canpanil'],
                    ['t', 'vec', 'canpanile'],
                    ['t', 'vec', 'canpanièl'],
                    ['t', 'vec', 'canpaniłe'],
                    ['trans-bottom'],
                    [
                        'trans-top',
                        'part of a large tower or steeple, specifically for containing bells',
                    ],
                    ['t', 'bg', 'камбанария'],
                    ['t+', 'fi', 'kellotorni'],
                    ['t+', 'de', 'Glockenstube', 'f'],
                    ['t+', 'el', 'κωδωνοστάσιο', 'n'],
                    ['t', 'ga', 'clogás', 'm'],
                    ['t+', 'ja', '鐘楼', 'tr=しょうろう, shōrō'],
                    ['t', 'mi', 'pourewa pere'],
                    ['trans-mid'],
                    ['t', 'nb', 'klokkerom', 'n'],
                    ['t', 'nn', 'klokkerom', 'n'],
                    ['t+', 'pt', 'campanário', 'm'],
                    ['t', 'rm', 'clutger', 'm'],
                    [
                        'qualifier',
                        'Rumantsch Grischun, Sursilvan, Sutsilvan, Surmiran',
                    ],
                    ['t', 'rm', 'clucher', 'm'],
                    ['qualifier', 'Puter, Vallader'],
                    ['t+', 'es', 'campanario', 'm'],
                    ['t', 'tl', 'batingawan'],
                    ['trans-bottom'],
                ],
            },
            _objects: [
                ['en-noun', 'belfries'],
                ['lb', 'en', 'obsolete'],
                ['lb', 'en', 'dialectal'],
                ['lb', 'en', 'obsolete'],
                ['lb', 'en', 'architecture'],
                ['lb', 'en', 'architecture'],
                ['RQ:Joyce Ulysses'],
            ],
        }
    );
    expect(actual.word).toBe('belfry');
    expect(actual.grammaticalNumber).toBe('singular');
    expect(actual.singularForm).toBe('belfry');
});

test('noun plural', () => {
    const actual = parseNoun(
        {
            word: 'belfries',
            alternativeForms: [],
            derivedTerms: [],
            relatedTerms: [],
            pronunciations: [{ tags: [], ipa: '/ˈbɛlfɹiz/' }],
            rhymes: [],
            anagrams: [],
            etymology: '',
        },
        {
            _content: [
                '{{head|en|noun form}}',
                '',
                '# {{plural of|belfry|lang=en}}',
                '',
            ],
            _objects: [
                ['head', 'en', 'noun form'],
                ['plural of', 'belfry', 'lang=en'],
            ],
        }
    );
    expect(actual.word).toBe('belfries');
    expect(actual.grammaticalNumber).toBe('plural');
    expect(actual.singularForm).toBe('belfry');
});

test('noun plural no singular form', () => {
    const actual = parseNoun(
        {
            word: 'belfries',
            alternativeForms: [],
            derivedTerms: [],
            relatedTerms: [],
            pronunciations: [{ tags: [], ipa: '/ˈbɛlfɹiz/' }],
            rhymes: [],
            anagrams: [],
            etymology: '',
        },
        {
            _content: [
                '{{head|en|noun form}}',
                '',
                '# {{plural of|lang=en}}',
                '',
            ],
            _objects: [['head', 'en', 'noun form'], ['plural of', 'lang=en']],
        }
    );
    expect(actual.singularForm).toBe('');
    expect(actual.grammaticalNumber).toBe('plural');
});
